import { GoogleGenerativeAI, type Part } from '@google/generative-ai';

const SYSTEM_PROMPT = `You are an expert frontend developer. You will receive Figma design context data generated by the Figma MCP (Model Context Protocol) tool.

## Input format
The Figma MCP tool outputs React + Tailwind CSS code that represents the design structure. It includes:
- React component code with Tailwind class names (e.g. className="flex gap-4 ...")
- Image asset URLs from a local Figma server (e.g. http://localhost:3845/assets/...)
- Design tokens such as font families, sizes, colors in CSS variable format
- Node IDs as data-node-id attributes for reference

## Your task
Convert this React + Tailwind design context into a COMPLETE, SELF-CONTAINED HTML document (<!DOCTYPE html> ... </html>) that visually reproduces the design as accurately as possible.

## Rules
- Load Tailwind CSS via CDN: <script src="https://cdn.tailwindcss.com"></script>
- Preserve all exact colors, spacing, typography, and layout from the design context
- Keep image URLs exactly as provided (http://localhost:3845/assets/...) — they are served locally
- If a design token CSS variable is referenced (e.g. var(--spacing/static/static_400,16px)), use the fallback value
- The output MUST be a single HTML file renderable in an <iframe srcdoc> attribute
- Do NOT wrap the output in markdown code blocks. Return raw HTML only
- Do NOT omit content or simplify the design — reproduce it faithfully`;

export async function generateHtml(params: {
  apiKey: string;
  model: string;
  mcpData: string;
  prompt: string;
  localAppUrl?: string;
  screenshot?: { data: string; mimeType: string };
}): Promise<{ html: string; rawResponse: string }> {
  const { apiKey, model, mcpData, prompt, screenshot } = params;

  const genAI = new GoogleGenerativeAI(apiKey);
  const geminiModel = genAI.getGenerativeModel({
    model,
    systemInstruction: SYSTEM_PROMPT,
  });

  let content: string | Part[];

  if (screenshot) {
    // 멀티모달: 스크린샷 이미지 + 텍스트
    const parts: Part[] = [
      { inlineData: { mimeType: screenshot.mimeType, data: screenshot.data } },
    ];
    if (mcpData.trim()) {
      parts.push({ text: `## Figma MCP Data (참고용)\n${mcpData}` });
    }
    parts.push({
      text: `## Additional Instructions\n${prompt || '위 Figma 디자인 스크린샷을 그대로 HTML로 구현해줘. 이미지 애셋은 http://localhost:3845/assets/ 경로를 사용해줘.'}`,
    });
    content = parts;
  } else {
    // 텍스트 전용
    content = `## Figma MCP Data\n${mcpData}\n\n## Additional Instructions\n${prompt}`;
  }

  const result = await geminiModel.generateContent(content);
  const rawResponse = result.response.text();

  const html = extractHtml(rawResponse);

  return { html, rawResponse };
}

function extractHtml(raw: string): string {
  // 코드블록 내 HTML 추출
  const codeBlockMatch = raw.match(/```(?:html)?\s*([\s\S]*?)```/i);
  if (codeBlockMatch) {
    return codeBlockMatch[1].trim();
  }

  // DOCTYPE으로 시작하는 경우
  const doctypeIdx = raw.indexOf('<!DOCTYPE');
  if (doctypeIdx !== -1) {
    return raw.slice(doctypeIdx).trim();
  }

  // <html>로 시작하는 경우
  const htmlIdx = raw.indexOf('<html');
  if (htmlIdx !== -1) {
    return raw.slice(htmlIdx).trim();
  }

  // 어떤 경우도 아니라면 템플릿으로 래핑
  return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Generated</title>
  <style>body { font-family: sans-serif; padding: 24px; }</style>
</head>
<body>
${raw}
</body>
</html>`;
}
